"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .removedincomingmessage import (
    RemovedIncomingMessage,
    RemovedIncomingMessageTypedDict,
)
from gsmservice_gateway.types import BaseModel
from gsmservice_gateway.utils import FieldMetadata, PathParamMetadata
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class RemoveIncomingMessagesRequestTypedDict(TypedDict):
    ids: List[int]
    r"""List[str] with Message IDs assigned by the system. The system will accept a maximum of 50 identifiers in one call."""


class RemoveIncomingMessagesRequest(BaseModel):
    ids: Annotated[
        List[int], FieldMetadata(path=PathParamMetadata(style="simple", explode=True))
    ]
    r"""List[str] with Message IDs assigned by the system. The system will accept a maximum of 50 identifiers in one call."""


class RemoveIncomingMessagesResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: List[RemovedIncomingMessageTypedDict]


class RemoveIncomingMessagesResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: List[RemovedIncomingMessage]
